### PR TITLE
OCPBUGS-11885: Add ability to debug LPM lookups

### PR DESCRIPTION
**Pull request by msherif1234**
**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by martinkennelly — CHANGES_REQUESTED** [review]
so previous to this change we updated the debug map always but following this change, its configurable right?

**Comment by msherif1234** [comment]
> so previous to this change we updated the debug map always but following this change, its configurable right?

Correct to avoid performance impact

**Pull request merged**
