### PR TITLE
Remove binaries from bin/ and fix .gitignore

### PR DESCRIPTION
**Pull request by andreaskaris**
That unfortunately won't prune the 60 mb from the repo, but at least it'll prevent that from happening in the future

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

**- What this PR does and why is it needed**

**- Special notes for reviewers**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by msherif1234** [comment]
You need to keep ebpf.o files

**Comment by andreaskaris** [comment]
But wouldn't I do something like:
~~~
container: ebpf-generate
    buildah bud . -t <container name>
~~~

So every time I build the container, the ebpf object files a created at that moment? Isn't it bad practive to have binary files checked into a repo?

**Comment by msherif1234** [comment]
> But wouldn't I do something like:
> 
> ```
> container: ebpf-generate
>     buildah bud . -t <container name>
> ```
> 
> So every time I build the container, the ebpf object files are created at that moment? Isn't it bad practice to have binary files checked into a repo?

All app using cilium they checked in generated .o so I didn’t feel bad including them we can open issue to remove them and explore options but later

**Pull request merged**
