### PR TITLE
Move webhook to its own package

### PR DESCRIPTION
**Pull request by martinkennelly**
This will allow API consumers not to have to import our
webhook imports when they just want to consume the API.

Signed-off-by: Martin Kennelly <mkennell@redhat.com>

/cc @msherif1234

### CODE REVIEW

**Comment by msherif1234** [comment]
While you are here can add something for webhook in e2e

**Comment by martinkennelly** [comment]
> While you are here can add something for webhook in e2e

Sure. Good idea.

**Comment by msherif1234** [comment]
fix #78

**Pull request merged**
