### PR TITLE
E2E test: only pay attention to internal IPs only and explicitly check for ipv6 address

### PR DESCRIPTION
**Pull request by martinkennelly**
Signed-off-by: Martin Kennelly <mkennell@redhat.com>

Comment from @msherif1234 that wasn't addressed in #173

### CODE REVIEW

**Comment by msherif1234** [comment]
yeah I called out that during E2E PR didn't double check the last diffs I assumed it was done :(
/lgtm
/approve

**Comment by martinkennelly** [comment]
Tested it with KinD and `ip.To16()` acts as expected.

**Pull request merged**
