### PR TITLE
OCPBUGS-22756: update manifset operator image

### PR DESCRIPTION
**Pull request by msherif1234**
**- What this PR does and why is it needed**
update operator image in the csv

### CODE REVIEW

**Review by sosiouxme — COMMENTED** [review]
ART is only looking at `/manifests/stable/ingress-node-firewall.clusterserviceversion.yaml`

and the important bit is that only references in `/manifests/stable/image-references` will get replaced (the replacement is by string, not semantic). so currently ART will replace `quay.io/openshift/origin-ingress-node-firewall:latest`; it won't replace `quay.io/openshift/ingress-node-firewall-operator:latest`

**Review by sosiouxme — APPROVED** [review]
/lgtm

**Comment by ashwindasr** [comment]
I see that the test `ci/prow/ingress-node-firewall-e2e-metal-ipi ` succeeded but the PR isn't being updated. Issue with with github bot? :thinking:

**Pull request merged**
