### PR TITLE
OCPBUGS-1435: added suggest ns to manifest

### PR DESCRIPTION
**Pull request by msherif1234**
Add suggested name space to manifest just to give users different options
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>

### CODE REVIEW

**Comment by martinkennelly** [comment]
@msherif1234 Why isnt the namespace openshift-ingress-node-firewall?

**Comment by msherif1234** [comment]
> @msherif1234 Why isnt the namespace openshift-ingress-node-firewall?
> 
> > Add suggested name space to manifest just to give users different options
> 
> Is this implying that ` operatorframework.io/suggested-namespace` is an alternative namespace suggestion? I tried to find docs for this and failed. Would appreciate if you have a link.

If you check the image in bug it doesn’t give you option to change ns this keyword apparently enable this fou f that out for similar pr got metallb operator

**Comment by martinkennelly** [comment]
/lgtm
Thanks for the explanation.

**Pull request merged**
